collections:
  - facilities

description: Located at the foot of Mt. Rinjani, Tetebatu is encircled with lush rice terraces and waterfalls. The village is wonderfully unspoiled by mass tourism but travellers are welcomed by friendly locals, abundant accomodation and delicious food.

